#########################################################
# Environment Setting
gpu_id: 0
log_wandb: True
wandb_project: 'Books_Recommendation'
data_path: './data/'
#########################################################
# Data Setting

## Atomic File Format
field_separator: "\t"
seq_separator: " "

## Common Features
USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'item_id'
TIME_FIELD: 'timestamp'
RATING_FIELD: 'rating'
# seq_len: None

## label for Point-wise Dataloader
threshold:
    rating: 3

## Sequential model
# ITEM_LIST_LENGTH_FIELD (str) : Field name of the feature representing item sequences’ length. Defaults to item_length.

# LIST_SUFFIX (str) : Suffix of field names which are generated as sequences. E.g. if we have item ID named item_id, then those item ID sequences will be called item_id + LIST_SUFFIX. Defaults to _list.

# MAX_ITEM_LIST_LENGTH (int): Maximum length of each generated sequence. Defaults to 50.

# POSITION_FIELD (str) : Field name of the generated position sequence. For sequence of length k, its position sequence is range(k). Note that this field will only be generated if this arg is not None. Defaults to position_id.

## Selectively
load_col:
    inter: ['user_id', 'item_id', 'rating', 'timestamp']
    user: ['user_id', 'user_overall_diversity', 'user_overall_mean', 'user_years', 'user_book_count']
    item: ['item_id', 'item_overall_mean', 'item_first_year', 'item_user_count']

unused_col:
    inter: ['timestamp']
#########################################################
# Training Setting
epochs: 100
train_batch_size: 2048
learner: 'adam'
learning_rate: 0.001
# neg_sampling: None
    # uniform: 1
    # dynamic: 2
eval_step: 1
stopping_step: 5
#########################################################
# Evaluation Setting
eval_args:
    group_by: user
    order: RO
    split:
        RS: [8, 1, 1]
    # mode: 'labeled'
    mode: full
metrics: ['Recall', 'MRR', 'NDCG', 'Hit', 'Precision']
topk: 10
valid_metric: Recall@10
eval_batch_size: 4096
#########################################################
# Hyperparameter